# Generated by Django 3.2 on 2021-04-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppThree', '0005_userprofileinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserList',
            new_name='VisitorList',
        ),
    ]
